CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Homo            ------------------------------------------------------------
Hyaena          MQVLAGRPGASPRSFTPAVTKARPPSRRGYKAAGRPPRRARLPGSTHAPRRGQACAQLQA
Toxoplasma      ------------------------------------------------------------
Sus             ------------------------------------------------------------
Camelus         ------------------------------------------------------------
                                                                            

Homo            ------MKWVWALLLLAALGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLF
Hyaena          GGLLSTMAWVWALVLLAALGSAQAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLF
Toxoplasma      ------MEWVWALVLLAALGSAQAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLF
Sus             ------MEWVWALVLLAALGSAQAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLF
Camelus         ------MEWVWALMLLAALGSARAERDCRVSSFRVKENFDKARFAGTWYAMAKKDPEGLF
                      * *****:*******..*********************:***************

Homo            LQDNIVAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASF
Hyaena          LQDNIVAEFSVDENGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDSAKFKMKYWGVASF
Toxoplasma      LQDNIVAEFSVDENGHMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASF
Sus             LQDNIVAEFSVDENGHMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASF
Camelus         LQDNIIAEFSVDENGHMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASF
                *****:*******.*:******************************.*************

Homo            LQKGNDDHWIVDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQKIVRQRQ
Hyaena          LQKGNDDHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFARDPKGLPPDVQKIVRQRQ
Toxoplasma      LQKGNDDHWIIDTDYDTYAVQYSCRLQNLDGTCADSYSFVFARDPHGFSPEVQKIVRQRQ
Sus             LQKGNDDHWIIDTDYDTYAVQYSCRLQNLDGTCADSYSFVFARDPHGFSPEVQKIVRQRQ
Camelus         LQKGNDDHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFARDPYGFSPEVQKIVRQRQ
                **********:*************** **************:*** *:.*:.********

Homo            EELCLARQYRLIVHNGYCDGRSERNLL
Hyaena          DELCLARQYRLIVHNGYCDGKSEQNIL
Toxoplasma      EELCLARQYRLITHNGYCDGKSERNIL
Sus             EELCLARQYRLITHNGYCDGKSERNIL
Camelus         EELCLARQYRLIVHNGYCDGKSERNIL
                :***********.*******.**.*:*
